version: '3'
services:
  app:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=staging
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
      - "3001:3001"
    command: ["nodemon", "index.js"]
    user: "1000"