version: '3'
services:
  app:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=staging
      # - NODE_ENV=production
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5000:5000"
      - "5001:5001"
    command: ["nodemon", "index.js"]